// API services barrel — re-exports for cleaner imports
export { apiClient } from './client'
export * as authApi from './auth'
export { analyticsService } from './analytics'
export { analyticsV2Service } from './analyticsV2'
export { calculationsApi } from './calculations'
export { preferencesService } from './preferences'
export { transactionsService } from './transactions'
export { uploadService } from './upload'
export { reportsApi } from './reports'
export { accountClassificationsService } from './accountClassifications'
export { categorizationRulesService } from './categorizationRules'
export type { CategorizationRule, CategorizationRuleInput } from './categorizationRules'
export { savedViewsService } from './savedViews'
export type { SavedView } from './savedViews'
