"""add user_id to aggregation tables

Revision ID: cc9fa860116e
Revises: add_user_auth
Create Date: 2026-02-06 08:37:34.591457

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc9fa860116e"
down_revision: str | None = "add_user_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _existing_indexes(table: str) -> set[str]:
    """Reflect the index names currently on ``table``.

    The autogenerated drop/recreate pairs below assume the index names that
    ``create_all()`` produces (``ix_<table>_<column>``), but the migration that
    created these tables named them differently (``ix_fy_summary_year``,
    ``ix_merchant_name``, ``ix_monthly_summary_period``). On a database built
    from migrations those names never exist, so the drops have to be
    conditional or batch-mode reflection raises ``No such index``.
    """
    inspector = sa.inspect(op.get_bind())
    return {idx["name"] for idx in inspector.get_indexes(table) if idx.get("name")}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop legacy transfers table (transfers now handled in transactions table)
    # Use DROP TABLE IF EXISTS since indexes may or may not exist depending
    # on whether schema was created via migrations or create_all().
    op.execute(sa.text("DROP TABLE IF EXISTS transfers"))

    # Truncate all aggregation tables before adding NOT NULL user_id column.
    # These are pre-calculated analytics that get rebuilt on next upload.
    aggregation_tables = [
        "anomalies",
        "budgets",
        "category_trends",
        "financial_goals",
        "fy_summaries",
        "merchant_intelligence",
        "monthly_summaries",
        "net_worth_snapshots",
        "recurring_transactions",
        "transfer_flows",
    ]
    for table in aggregation_tables:
        # Table names come from the hardcoded list above, never from user input.
        op.execute(sa.text(f"DELETE FROM {table}"))

    # Use batch_alter_table for SQLite compatibility (no ALTER FK support).
    # For each table: add user_id column, create indexes, add FK to users.

    with op.batch_alter_table("anomalies") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index(op.f("ix_anomalies_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_anomaly_user", ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_anomalies_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("budgets") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index(op.f("ix_budgets_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_budgets_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("category_trends") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index("ix_category_trend_user", ["user_id"], unique=False)
        batch_op.create_index(op.f("ix_category_trends_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_category_trends_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("financial_goals") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index(op.f("ix_financial_goals_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_financial_goals_user_id", "users", ["user_id"], ["id"])

    fy_indexes = _existing_indexes("fy_summaries")
    with op.batch_alter_table("fy_summaries") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        if "ix_fy_summaries_fiscal_year" in fy_indexes:
            batch_op.drop_index(op.f("ix_fy_summaries_fiscal_year"))
        batch_op.create_index(op.f("ix_fy_summaries_fiscal_year"), ["fiscal_year"], unique=False)
        batch_op.create_index(op.f("ix_fy_summaries_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_fy_summaries_user_id", "users", ["user_id"], ["id"])

    merchant_indexes = _existing_indexes("merchant_intelligence")
    with op.batch_alter_table("merchant_intelligence") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        if "ix_merchant_intelligence_merchant_name" in merchant_indexes:
            batch_op.drop_index(op.f("ix_merchant_intelligence_merchant_name"))
        batch_op.create_index(
            op.f("ix_merchant_intelligence_merchant_name"), ["merchant_name"], unique=False
        )
        batch_op.create_index(op.f("ix_merchant_intelligence_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_merchant_intelligence_user_id", "users", ["user_id"], ["id"]
        )

    monthly_indexes = _existing_indexes("monthly_summaries")
    with op.batch_alter_table("monthly_summaries") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        if "ix_monthly_summaries_period_key" in monthly_indexes:
            batch_op.drop_index(op.f("ix_monthly_summaries_period_key"))
        batch_op.create_index(op.f("ix_monthly_summaries_period_key"), ["period_key"], unique=False)
        batch_op.create_index(op.f("ix_monthly_summaries_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_monthly_summary_user_period", ["user_id", "period_key"], unique=True
        )
        batch_op.create_foreign_key("fk_monthly_summaries_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("net_worth_snapshots") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index(op.f("ix_net_worth_snapshots_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_net_worth_user", ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_net_worth_snapshots_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("recurring_transactions") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_index(op.f("ix_recurring_transactions_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_recurring_user", ["user_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_recurring_transactions_user_id", "users", ["user_id"], ["id"]
        )

    with op.batch_alter_table("transfer_flows") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_index(op.f("ix_transfer_flow_accounts"))
        batch_op.create_index(
            "ix_transfer_flow_accounts", ["user_id", "from_account", "to_account"], unique=True
        )
        batch_op.create_index(op.f("ix_transfer_flows_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key("fk_transfer_flows_user_id", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transfer_flows", type_="foreignkey")
    op.drop_index(op.f("ix_transfer_flows_user_id"), table_name="transfer_flows")
    op.drop_index("ix_transfer_flow_accounts", table_name="transfer_flows")
    op.create_index(
        op.f("ix_transfer_flow_accounts"),
        "transfer_flows",
        ["from_account", "to_account"],
        unique=1,
    )
    op.drop_column("transfer_flows", "user_id")
    op.drop_constraint(None, "recurring_transactions", type_="foreignkey")
    op.drop_index("ix_recurring_user", table_name="recurring_transactions")
    op.drop_index(op.f("ix_recurring_transactions_user_id"), table_name="recurring_transactions")
    op.drop_column("recurring_transactions", "user_id")
    op.drop_constraint(None, "net_worth_snapshots", type_="foreignkey")
    op.drop_index("ix_net_worth_user", table_name="net_worth_snapshots")
    op.drop_index(op.f("ix_net_worth_snapshots_user_id"), table_name="net_worth_snapshots")
    op.drop_column("net_worth_snapshots", "user_id")
    op.drop_constraint(None, "monthly_summaries", type_="foreignkey")
    op.drop_index("ix_monthly_summary_user_period", table_name="monthly_summaries")
    op.drop_index(op.f("ix_monthly_summaries_user_id"), table_name="monthly_summaries")
    op.drop_index(op.f("ix_monthly_summaries_period_key"), table_name="monthly_summaries")
    op.create_index(
        op.f("ix_monthly_summaries_period_key"), "monthly_summaries", ["period_key"], unique=1
    )
    op.drop_column("monthly_summaries", "user_id")
    op.drop_constraint(None, "merchant_intelligence", type_="foreignkey")
    op.drop_index(op.f("ix_merchant_intelligence_user_id"), table_name="merchant_intelligence")
    op.drop_index(
        op.f("ix_merchant_intelligence_merchant_name"), table_name="merchant_intelligence"
    )
    op.create_index(
        op.f("ix_merchant_intelligence_merchant_name"),
        "merchant_intelligence",
        ["merchant_name"],
        unique=1,
    )
    op.drop_column("merchant_intelligence", "user_id")
    op.drop_constraint(None, "fy_summaries", type_="foreignkey")
    op.drop_index(op.f("ix_fy_summaries_user_id"), table_name="fy_summaries")
    op.drop_index(op.f("ix_fy_summaries_fiscal_year"), table_name="fy_summaries")
    op.create_index(op.f("ix_fy_summaries_fiscal_year"), "fy_summaries", ["fiscal_year"], unique=1)
    op.drop_column("fy_summaries", "user_id")
    op.drop_constraint(None, "financial_goals", type_="foreignkey")
    op.drop_index(op.f("ix_financial_goals_user_id"), table_name="financial_goals")
    op.drop_column("financial_goals", "user_id")
    op.drop_constraint(None, "category_trends", type_="foreignkey")
    op.drop_index(op.f("ix_category_trends_user_id"), table_name="category_trends")
    op.drop_index("ix_category_trend_user", table_name="category_trends")
    op.drop_column("category_trends", "user_id")
    op.drop_constraint(None, "budgets", type_="foreignkey")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_column("budgets", "user_id")
    op.drop_constraint(None, "anomalies", type_="foreignkey")
    op.drop_index("ix_anomaly_user", table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_user_id"), table_name="anomalies")
    op.drop_column("anomalies", "user_id")
    op.create_table(
        "transfers",
        sa.Column("transfer_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("date", sa.DATETIME(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.VARCHAR(length=10), nullable=False),
        sa.Column("type", sa.VARCHAR(length=12), nullable=False),
        sa.Column("from_account", sa.VARCHAR(length=255), nullable=False),
        sa.Column("to_account", sa.VARCHAR(length=255), nullable=False),
        sa.Column("category", sa.VARCHAR(length=255), nullable=False),
        sa.Column("subcategory", sa.VARCHAR(length=255), nullable=True),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("source_file", sa.VARCHAR(length=500), nullable=False),
        sa.Column("last_seen_at", sa.DATETIME(), nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("transfer_id"),
    )
    op.create_index(op.f("ix_transfers_type"), "transfers", ["type"], unique=False)
    op.create_index(op.f("ix_transfers_to_account"), "transfers", ["to_account"], unique=False)
    op.create_index(op.f("ix_transfers_last_seen_at"), "transfers", ["last_seen_at"], unique=False)
    op.create_index(op.f("ix_transfers_is_deleted"), "transfers", ["is_deleted"], unique=False)
    op.create_index(
        op.f("ix_transfers_from_to"), "transfers", ["from_account", "to_account"], unique=False
    )
    op.create_index(op.f("ix_transfers_from_account"), "transfers", ["from_account"], unique=False)
    op.create_index(op.f("ix_transfers_date_type"), "transfers", ["date", "type"], unique=False)
    op.create_index(op.f("ix_transfers_date"), "transfers", ["date"], unique=False)
    op.create_index(op.f("ix_transfers_category"), "transfers", ["category"], unique=False)
    # ### end Alembic commands ###
