# Alembic migration environment configuration
# Generated by Alembic - DO NOT EDIT manually

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Import application config and models
from ledger_sync.config.settings import settings

# Import ALL models for autogenerate detection
from ledger_sync.db import models  # noqa: F401
from ledger_sync.db.base import Base

# this is the Alembic Config object
config = context.config

# Set SQLAlchemy URL from application settings.
# Normalise to psycopg (v3) driver — same logic as session.py.
_db_url = settings.database_url
if _db_url.startswith(("postgresql://", "postgresql+psycopg2://")):
    _db_url = _db_url.replace("postgresql+psycopg2://", "postgresql+psycopg://", 1)
    _db_url = _db_url.replace("postgresql://", "postgresql+psycopg://", 1)
config.set_main_option("sqlalchemy.url", _db_url)

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Add your model's MetaData object here for 'autogenerate' support
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
